# Generated by Django 4.2.6 on 2023-12-27 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sourcing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='numSources',
            field=models.IntegerField(),
        ),
    ]
